# Generated by Django 3.2.2 on 2021-07-17 10:31

from django.db import migrations, models
import django.db.models.deletion
import utils.upload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=255, verbose_name='Артикул')),
                ('name', models.CharField(max_length=255, verbose_name='Марка')),
                ('status', models.CharField(max_length=255, verbose_name='Состояние')),
                ('production_date', models.SmallIntegerField(default=2000, verbose_name='Год выпуска')),
                ('picture', models.ImageField(upload_to=utils.upload.upload_instance, verbose_name='Изображение')),
                ('started_price', models.SmallIntegerField(default=0, verbose_name='Начальная цена')),
                ('data_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubmitApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('picture', models.ImageField(upload_to=utils.upload.upload_instance, verbose_name='Фото машины')),
                ('data_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_after_step_up', models.CharField(max_length=255, verbose_name='Цена после повышения')),
                ('step_up_price', models.CharField(max_length=255, verbose_name='Цена повышения')),
                ('finished_price', models.CharField(max_length=255, verbose_name='Цена продажи')),
                ('in_progress', models.BooleanField(default=False, verbose_name='Текущий аукцион')),
                ('finished', models.BooleanField(default=False, verbose_name='Завершенный аукцион')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.cardetail', verbose_name='Машина')),
            ],
        ),
    ]
