# Generated by Django 3.2.2 on 2021-07-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='check_accepted',
            field=models.BooleanField(default=False, verbose_name='Подтверждение регистрации'),
        ),
    ]
